export { MonitoringPage } from './Monitoring'
export { CalibrationPage } from './Calibration'
export { CompliancePage } from './Compliance'
export { Desenquadramento } from './Desenquadramento'
export { RegistroDiario } from './RegistroDiario'
